### ISSUE TITLE
Crash on some VM Linux systems

### ISSUE THREAD

**Issue by Horcrux7** [dbmdz/imageio-jnr#192] opened 2022-03-21 15:43 UTC
On some combinations of Linux and Java VM we have a crash of the Java VM with imageio-openjpeg. For example on Ubuntu 21 and Java 11 or Alpine/Docker with Java 17. Any idea for the cause?

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.kenai.jffi.Foreign.invokeN3O1(JJJJJLjava/lang/Object;III)J+0
j  com.kenai.jffi.Invoker.invokeN3(Lcom/kenai/jffi/CallContext;JJJJILjava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;Ljava/lang/Object;Lcom/kenai/jffi/ObjectParameterStrategy;Lcom/kenai/jffi/ObjectParameterInfo;)J+126
j  de.digitalcollections.openjpeg.lib.libopenjp2$jnr$ffi$0.opj_read_header(Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;Ljnr/ffi/byref/PointerByReference;)Z+190
j  de.digitalcollections.openjpeg.OpenJpeg.getImage(Ljnr/ffi/Pointer;Ljnr/ffi/Pointer;)Lde/digitalcollections/openjpeg/lib/structs/opj_image;+32
j  de.digitalcollections.openjpeg.OpenJpeg.getInfo(Ljnr/ffi/Pointer;)Lde/digitalcollections/openjpeg/Info;+13
j  de.digitalcollections.openjpeg.OpenJpeg.getInfo(Lde/digitalcollections/openjpeg/InStreamWrapper;)Lde/digitalcollections/openjpeg/Info;+5
j  de.digitalcollections.openjpeg.imageio.OpenJp2ImageReader.getInfo()Lde/digitalcollections/openjpeg/Info;+16
j  de.digitalcollections.openjpeg.imageio.OpenJp2ImageReader.checkIndex(I)V+2
j  de.digitalcollections.openjpeg.imageio.OpenJp2ImageReader.read(ILjavax/imageio/ImageReadParam;)Ljava/awt/image/BufferedImage;+2
j  javax.imageio.ImageIO.read(Ljavax/imageio/stream/ImageInputStream;)Ljava/awt/image/BufferedImage;+56 java.desktop@17.0.2
j  javax.imageio.ImageIO.read(Ljava/io/InputStream;)Ljava/awt/image/BufferedImage;+35 java.desktop@17.0.2
j  com.inet.jpeg2000.Jpeg2000ServerPlugin.a(Lcom/inet/plugin/ServerPluginManager;)V+366

```
[hs_err_pid165.log](https://github.com/dbmdz/imageio-jnr/files/8316803/hs_err_pid165.log)

**Comment by jbaiter** [comment] 2022-03-22 20:47
Can you get your hands on a core dump and extract a backtrace for the parts beyond the FFI where the crash happens?

**Comment by jbaiter** [comment] 2022-03-23 16:22
Brilliant, thank you, I'll investigate!

**Comment by jbaiter** [comment] 2022-03-23 16:30
OK, so I could not reproduce the crash on my machine (Debian unstable, so pretty close to Ubuntu 21, OpenJDK 17.0.2 2022-01-18, x86_64). I also tried with OpenJDK 11.0.14 2022-01-18, also no crash.
Can you provide more details on your two environments, or maybe even a minimal Dockerfile for either of the two in the reproduction repo?

**Comment by gamma** [comment] 2022-03-23 16:49
We also added an issue with the JDK here: https://github.com/adoptium/adoptium-support/issues/477

Maybe there is additional valuable information for you.

**Comment by jbaiter** [comment] 2022-03-23 17:18
Thank you! The stock image is missing your musl-linked version of `libopenjp2.so.7` in `/tmp/openjpeg`, can you upload that somewhere?

**Comment by jbaiter** [comment] 2022-03-24 06:28
Bingo,  I just ran it inside the Docker container mentioned above with the `libopenjp2` from the Alpine repository that was linked specifically against libmusl and the test runs without a problem.
I think the issue is that the `libopenjp2` was built against glibc and then relocated to musl, `ldd` prints some warnings as well:

```
/app # ldd /app/openjpeg/linux/libopenjp2.so.7
        /lib/ld-musl-x86_64.so.1 (0x7faa6ecb4000)
        libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7faa6ecb4000)
        libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7faa6ecb4000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7faa6ecb4000)
Error relocating /app/openjpeg/linux/libopenjp2.so.7: __vsnprintf_chk: symbol not found
Error relocating /app/openjpeg/linux/libopenjp2.so.7: __pow_finite: symbol not found
Error relocating /app/openjpeg/linux/libopenjp2.so.7: __fprintf_chk: symbol not found
Error relocating /app/openjpeg/linux/libopenjp2.so.7: __sprintf_chk: symbol not found
```

**Comment by gamma** [comment] 2022-03-24 06:55
Sweet. Good catch. I did not check the `libopenjp2` dependencies - just some others. That effectively means that _we_ have to use a different openjp2 lib (will check that right away) or some obscure way to have `glibc` present - which is possible afaik.

**Comment by jbaiter** [comment] 2022-03-24 07:00
Yes, I think the easiest way would be to rely on the distro-provided `libopenjp2`, or if that is not possible/desired, to ship a `x86_64-unknown-linux-musl` build in your JAR.
I'll close this issue since it's not a problem with the library itself.

**Closed by jbaiter** 2022-03-24 07:00 UTC
